owner: gnosischain
repo: chiado-uptime

sites:
  - name: "RPC"
    method: POST
    url: https://rpc.chiadochain.net/
    headers: ["Content-Type: application/json"]
    body: |
      {
        "method": "eth_blockNumber",
        "params":[],
        "id":1,
        "jsonrpc":"2.0"
      }
    
  - name: "Beacon RPC"
    url: https://rpc-gbc.chiadochain.net/eth/v1/beacon/headers

  - name: "Explorer"
    url: https://blockscout.chiadochain.net/

  - name: "Beacon Explorer"
    url: https://beacon.chiadochain.net/

  - name: "Forkmon"
    url: https://forkmon.chiadochain.net/

  - name: "Forkmon ETH2"
    url: https://eth2-forkmon.chiadochain.net/

  - name: "Ethstats"
    url: https://ethstats.chiadochain.net/

status-website:
  introTitle: "**Chiado** the GnosisChain Testnet"
  introMessage: Check the availability for Chiado Testnet services
  baseUrl: /chiado-uptime
  logoUrl: https://raw.githubusercontent.com/gnosis/chiado-uptime/master/assets/chiado-logo.svg
  name: Chiado
  assignees:
    - riccardo.dantoni
  theme: dark
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 23 * * *"
    summary: "0 0 * * *"
    uptime: "*/5 * * * *"