owner: gnosis
repo: chiado-uptime

sites:
  - name: Chiado RPC
    method: POST
    url: https://rpc.chiadochain.net/
    headers: ["Content-Type: application/json"]
    body: |
      {
        "method": "eth_blockNumber",
        "params":[],
        "id":1,
        "jsonrpc":"2.0"
      }
    
  - name: Chiado Beacon RPC
    url: https://rpc-gbc.chiadochain.net/

  - name: Explorer
    url: https://blockscout.chiadochain.net/

  - name: "Beacon Explorer"
    url: https://beacon.chiadochain.net/

  - name: "Forkmon"
    url: https://forkmon.chiadochain.net/

  - name: "Forkmon ETH2"
    url: https://forkmon-eth2.chiadochain.net/

  - name: "Ethstats"
    url: https://ethstats.chiadochain.net/

  - name: "CoW Protocol - Docs"
    url: https://docs.cow.fi

status-website:
  cname: status.chiadochain.net
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/gnosis/chiado-uptime/master/assets/chiado-logo.svg
  name: Upptime
  introTitle: "Status for Chiado Testnet"
  introMessage: Check the availability for Chiado Testnet services.
  navbar:
    - title: Status
      href: /
  assignees:
    - riccardo.dantoni
  theme: dark
  workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 23 * * *"
    staticSite: "0 1 * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "*/5 * * * *"